#!/bin/bash

set -e

source ../config.sh
source ../utils.sh

# 1. Check configuration variables availability
echo -e "${C_INFO}🔍 Checking Pre-requisites...${C_RESET}"
if [ -z "$SSH_HOME_PATH" ]; then
    echo -e "${C_ERROR}❌ Error: Missing configuration variables.${C_RESET}"
    exit 1
fi

# 2. Get Server Details (Sets $SELECTED_NAME)
select_server_interactive

echo -e "\nSelected: ${C_ERROR}$SELECTED_NAME${C_RESET} ($SELECTED_IP)"
echo -e "${C_WARN}⚠️  WARNING: DESTRUCTIVE ACTION${C_RESET}"

# 3. Safety Lock
echo -n ">  Type '$SELECTED_NAME' to confirm: "
read CONFIRMATION

if [ "$CONFIRMATION" != "$SELECTED_NAME" ]; then
    echo -e "${C_ERROR}❌ Name mismatch. Aborted.${C_RESET}"
    exit 1
fi

# 4. Destroy from Hetzner
echo -e "${C_ERROR}🔥 Destroying $SELECTED_NAME...${C_RESET}"
hcloud server delete "$SELECTED_ID"

# 5. Cleanup SSH Config & Capture Port
SAVED_PORT=""
if grep -q "Host $SELECTED_NAME" $SSH_HOME_PATH/config; then
     # Extract the Port associated with this Host block
     SAVED_PORT=$(awk "/Host $SELECTED_NAME/{flag=1; next} /Host /{flag=0} flag && /Port/ {print \$2}" $SSH_HOME_PATH/config | head -1)

     echo -e "${C_INFO}📝 Removing entry from $SSH_HOME_PATH/config...${C_RESET}"
     cp $SSH_HOME_PATH/config $SSH_HOME_PATH/config.bak

     # Remove the block and the comment
     sed -i "/Host $SELECTED_NAME/,/IdentityFile/d" $SSH_HOME_PATH/config
     sed -i "/Auto-generated by Hetzner IaCarus/d" $SSH_HOME_PATH/config
     sed -i -z 's/\n\n*/\n/g' $SSH_HOME_PATH/config
fi

# 6. Cleanup Known Hosts
echo -e "${C_INFO}🧹 Cleaning known_hosts (IP: $SELECTED_IP | Port: ${SAVED_PORT:-22})...${C_RESET}"
clean_known_hosts "$SELECTED_NAME" "$SELECTED_IP" "$SAVED_PORT"

echo -e "${C_SUCCESS}✅ $SELECTED_NAME has been obliterated.${C_RESET}"
