#!/bin/bash

set -e

source ../config.sh
source ../utils.sh

# 1. Check configuration variables availability
echo -e "\n${C_INFO}🔍 Checking Pre-requisites...${C_RESET}"
if [[ -z "$SSH_HOME_PATH" || -z "$SSH_PUBLIC_KEY_PATH" || -z "$SSH_PRIVATE_KEY_PATH" || -z "$VPS_BASE_NAME" || -z "$VPS_TYPE" || -z "$VPS_LOCATION" || -z "$VPS_IMAGE" || -z "$ENVIRONMENT" || -z "$VPS_ADMIN_USER" || -z "$LITESTREAM_VERSION" ]]; then
    echo -e "${C_ERROR}❌ Error: Missing configuration variables.${C_RESET}"
    exit 1
fi

# 1. Calculate Next VPS ID
LAST_ID=$(hcloud server list -o noheader -o columns=name | grep "$VPS_BASE_NAME" | sed "s/$VPS_BASE_NAME//" | sort -n | tail -1)
NEXT_ID=$(( ${LAST_ID:-0} + 1 ))
SERVER_NAME="${VPS_BASE_NAME}${NEXT_ID}"

# 2. Generate Random Port (1022 - 60022)
RAND_PREFIX=$((10 + RANDOM % 590))
SSH_PORT="${RAND_PREFIX}22"

echo -e "${C_SUCCESS}🖥  Target: $SERVER_NAME | Port: $SSH_PORT | Region: $VPS_LOCATION${C_RESET}"

# 3. Prepare Cloud Config
SSH_PUBLIC_KEY=$(cat "$SSH_PUBLIC_KEY_PATH")

sed -e "s|{{SSH_KEY}}|$SSH_PUBLIC_KEY|g" \
    -e "s|{{SSH_PORT}}|$SSH_PORT|g" \
    -e "s|{{USER}}|$VPS_ADMIN_USER|g" \
    -e "s|{{LITESTREAM_VERSION}}|$LITESTREAM_VERSION|g" \
    ./vps-user_data.yml.template > vps-user_data.yml

# 4. Provision via Hetzner CLI
echo -e "${C_INFO}☁️  Calling Hetzner API...${C_RESET}"
hcloud server create \
  --name "$SERVER_NAME" \
  --type "$VPS_TYPE" \
  --location "$VPS_LOCATION" \
  --image "$VPS_IMAGE" \
  --user-data-from-file vps-user_data.yml \
  --label env="$ENVIRONMENT"

rm vps-user_data.yml
SERVER_IP=$(hcloud server ip "$SERVER_NAME")

echo -e "${C_SUCCESS}✅ Server Created: $SERVER_IP${C_RESET}"

# 5. Update Local SSH Config
echo -e "${C_INFO}📝 Updating ${SSH_HOME_PATH}/config...${C_RESET}"
cp $SSH_HOME_PATH/config $SSH_HOME_PATH/config.bak

cat <<EOF >> $SSH_HOME_PATH/config

# Auto-generated by Hetzner IaCarus ($(date +%Y-%m-%d))
Host $SERVER_NAME
  HostName $SERVER_IP
  User $VPS_ADMIN_USER
  Port $SSH_PORT
  IdentityFile $SSH_PRIVATE_KEY_PATH
EOF

# 6. Wait for SSH (Cloud-Init)
echo -e "${C_INFO}⏳ Waiting for SSH (approx 45s)...${C_RESET}"

for i in {1..30}; do
    if nc -z -w 2 "$SERVER_IP" "$SSH_PORT" 2>/dev/null; then
        echo -e "\n${C_SUCCESS}⇄  Port $SSH_PORT is open!${C_RESET}"
        break
    fi
    echo -n "."
    sleep 3
done

echo "Stabilizing connection..."
sleep 5

# 7. Keyscan
echo -e "${C_INFO}🔑 Registering SSH Keys...${C_RESET}"

# Clean ANY previous record of this IP or [IP]:PORT to avoid conflicts
clean_known_hosts "$SERVER_NAME" "$SERVER_IP" "$SSH_PORT"

# Scan the CUSTOM port (Append to known_hosts). Backgrounded so we can print
# a progress counter - ssh-keyscan gives no feedback while it waits.
(
    ssh-keyscan -p "$SSH_PORT" "$SERVER_IP" 2>/dev/null | grep -v "^#" >> $SSH_HOME_PATH/known_hosts || true
    ssh-keyscan -p "$SSH_PORT" "$SERVER_NAME" 2>/dev/null | grep -v "^#" >> $SSH_HOME_PATH/known_hosts || true
) &
KEYSCAN_PID=$!

while kill -0 "$KEYSCAN_PID" 2>/dev/null; do
    echo -n "."
    sleep 1
done
wait "$KEYSCAN_PID"
echo -e "\n${C_SUCCESS}✅ Keys registered.${C_RESET}"

echo -e "------------------------------------------------"
echo -e "${C_SUCCESS}🎉 DEPLOYMENT COMPLETE!${C_RESET}"
echo -e "   ${C_WARN}It's strongly advised that you setup a Hetzner Firewall allowing ONLY the SSH PORT: ${SSH_PORT}${C_RESET}"
echo -e "   Login: ${C_SUCCESS}ssh $SERVER_NAME${C_RESET}"
echo -e "------------------------------------------------"
