#!/bin/bash

source ../config.sh
source ../utils.sh

# =============================================================================
# Make a provisioned MON box actually able to view the fleet (SPRINT B3).
#
# The cloud-init profile installs TOOLING only. Everything this script ships is
# operator state that must never appear in user-data, because Hetzner retains
# user-data and the metadata service serves it back to anything on the box:
#
#   1. the viewer itself      - mon/, config.sh, utils.sh (NOT the git remote,
#                               NOT the .git dir - just what mon/*.sh reads)
#   2. mon/registry.json      - which apps exist and where their health lives
#   3. a minimal .env         - MON_* tuning only. NO Hetzner token, NO
#                               Cloudflare keys. The box stays a CREDENTIAL-LESS
#                               viewer: mon_context() reports 'viewer', hardware
#                               targets come from the registry, apps are checked
#                               over their public URLs. A stolen mon box grants
#                               no infrastructure access.
#   4. an SSH KEY GENERATED ON THE BOX - the private half never leaves it and
#                               never existed anywhere else. We only ever carry
#                               the PUBLIC half back to authorize it on the app
#                               boxes. Copying your laptop's key here instead
#                               would hand full fleet control to a host whose
#                               whole point is being disposable.
#
# Idempotent - re-run it whenever the fleet or the registry changes.
# =============================================================================

echo -e "\n${C_INFO}📡 Setting up the MON viewer...${C_RESET}"

# 1. Pick the mon box. Filtered to the mon name prefix so an app box can't be
#    chosen by a slip of the finger - this script writes to /opt and installs
#    authorized_keys entries around the fleet.
echo -e "\n${C_INFO}🔍 Fetching mon boxes from Hetzner...${C_RESET}"

mapfile -t MON_BOXES < <(hcloud server list -o noheader -o columns=name | awk 'NF {print $1}' | grep "^${MON_VPS_BASE_NAME}" || true)

if [ ${#MON_BOXES[@]} -eq 0 ]; then
    echo -e "${C_ERROR}❌ No mon box found (looking for names starting '${MON_VPS_BASE_NAME}').${C_RESET}"
    echo -e "${C_INFO}   Create one with: ${C_RESET}${C_HIGH}make vps-new-mon${C_RESET}"
    exit 1
fi

if [ ${#MON_BOXES[@]} -eq 1 ]; then
    MON_BOX="${MON_BOXES[0]}"
    echo -e "   ${C_INFO}Using ${C_RESET}${C_HIGH}${MON_BOX}${C_RESET}"
else
    echo "Select the mon box:"
    PS3="Enter number (or 'q' to quit): "
    select ITEM in "${MON_BOXES[@]}"; do
        [[ "$REPLY" == "q" ]] && echo "Aborted." && exit 0
        [ -n "$ITEM" ] && MON_BOX="$ITEM" && break
        echo "Invalid selection."
    done
fi

# 2. Pre-Flight Connection Check
if ! check_ssh_access "$MON_BOX"; then
    exit 1
fi

# 3. Ship the viewer. A tar over stdin rather than scp/rsync: rsync is not
#    guaranteed on a freshly hardened box, and this keeps it to one round trip
#    with no temp files on either side. --exclude keeps secrets and local state
#    out by construction rather than by remembering to delete them after.
echo -e "\n${C_INFO}📦 Shipping the viewer to ${MON_REMOTE_PATH}...${C_RESET}"

ssh -q "$MON_BOX" "sudo mkdir -p '$MON_REMOTE_PATH' && sudo chown \$(id -un):\$(id -gn) '$MON_REMOTE_PATH'"

tar -C .. -cz \
    --exclude='.git' \
    --exclude='.env' \
    --exclude='doc' \
    mon config.sh utils.sh config.mk Makefile \
    | ssh -q "$MON_BOX" "tar -xz -C '$MON_REMOTE_PATH'"

echo -e "   ${C_SUCCESS}✅ mon/, config.sh, utils.sh, Makefile${C_RESET}"

# 4. Ship the registry separately - it is gitignored operator state and the one
#    file the app board cannot work without. Absent locally is not fatal: a
#    fresh clone may simply have no apps yet.
if [ -f "$MON_REGISTRY" ]; then
    ssh -q "$MON_BOX" "cat > '${MON_REMOTE_PATH}/mon/registry.json'" < "$MON_REGISTRY"
    APP_COUNT=$(jq 'length' "$MON_REGISTRY")
    echo -e "   ${C_SUCCESS}✅ registry.json (${APP_COUNT} app(s))${C_RESET}"
else
    echo -e "   ${C_WARN}⚠️  no local registry to ship - the app board will be empty${C_RESET}"
fi

# 5. Write the credential-less .env. config.sh EXITS if .env is missing, so the
#    box needs one - but it carries only MON_* tuning. Every infrastructure
#    secret is deliberately absent, which is what keeps mon_context() in
#    'viewer' mode and the box worthless to an attacker.
echo -e "\n${C_INFO}🔑 Writing a credential-less .env...${C_RESET}"

ssh -q "$MON_BOX" "cat > '${MON_REMOTE_PATH}/.env'" << EOF
# Generated by 'make vps-mon-setup' - IaCarus MON box.
#
# DELIBERATELY CREDENTIAL-LESS. No Hetzner token, no Cloudflare keys: this box
# is a stateless VIEWER. It reads the registry and checks public URLs, so it
# needs no infrastructure access and grants none if compromised.
# config.sh requires this file to exist; that is the only reason it is here.

# Latency thresholds are a property of the OBSERVER, not the app - this box
# sits next to the fleet, so it should judge far tighter than a laptop in
# Brazil. Tune to taste.
MON_LATENCY_WARN_MS=${MON_LATENCY_WARN_MS_REMOTE:-300}
MON_LATENCY_CRIT_MS=${MON_LATENCY_CRIT_MS_REMOTE:-1000}
EOF

echo -e "   ${C_SUCCESS}✅ .env (MON_* only - no infrastructure credentials)${C_RESET}"

# 6. Generate the box's OWN keypair, once. -N '' (no passphrase) because the
#    viewer must run unattended; the key's blast radius is bounded instead by
#    being a distinct key we can revoke from the fleet without touching yours.
echo -e "\n${C_INFO}🗝️  Ensuring the mon box has its own SSH identity...${C_RESET}"

MON_PUBKEY=$(ssh -q "$MON_BOX" '
    if [ ! -f ~/.ssh/id_ed25519 ]; then
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        ssh-keygen -q -t ed25519 -N "" -C "iacarus-mon-$(hostname)" -f ~/.ssh/id_ed25519
    fi
    cat ~/.ssh/id_ed25519.pub')

if [ -z "$MON_PUBKEY" ]; then
    echo -e "${C_ERROR}❌ Could not read the mon box public key.${C_RESET}"
    exit 1
fi

echo -e "   ${C_SUCCESS}✅ ${MON_PUBKEY:0:48}...${C_RESET}"

# 7. Authorize that key on every APP box, and teach the mon box how to reach
#    them. The mon box has no Hetzner credentials, so it cannot discover ports
#    or IPs itself - we resolve them HERE (where the creds are) and write the
#    result into its ssh config. That is precisely the operator/viewer split:
#    provisioning knowledge stays on the operator machine, the viewer gets only
#    the addresses it needs.
echo -e "\n${C_INFO}🔗 Linking the mon box to the app boxes...${C_RESET}"

mapfile -t APP_BOXES < <(hcloud server list -o noheader -o columns=name | awk 'NF {print $1}' | grep -v "^${MON_VPS_BASE_NAME}" || true)

if [ ${#APP_BOXES[@]} -eq 0 ]; then
    echo -e "   ${C_WARN}⚠️  No app boxes found - nothing to link.${C_RESET}"
fi

SSH_CONFIG_BLOCK=""

for BOX in "${APP_BOXES[@]}"; do
    # Read the port/host/user we already hold locally for this box, so the mon
    # box's config matches the operator's exactly (randomized ports mean it
    # cannot be guessed).
    BOX_PORT=$(ssh -G "$BOX" 2>/dev/null | awk '/^port /{print $2; exit}')
    BOX_HOST=$(ssh -G "$BOX" 2>/dev/null | awk '/^hostname /{print $2; exit}')
    BOX_USER=$(ssh -G "$BOX" 2>/dev/null | awk '/^user /{print $2; exit}')

    if [ -z "$BOX_HOST" ] || [ "$BOX_HOST" = "$BOX" ]; then
        echo -e "   ${C_WARN}⚠️  ${BOX} skipped - no local ssh config entry to copy${C_RESET}"
        continue
    fi

    # Install the mon key on the app box. Appended only if absent, so re-running
    # never duplicates the line.
    if ssh -q -n -o BatchMode=yes -o ConnectTimeout=8 "$BOX" \
        "mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && grep -qxF '$MON_PUBKEY' ~/.ssh/authorized_keys || echo '$MON_PUBKEY' >> ~/.ssh/authorized_keys" 2>/dev/null; then
        echo -e "   ${C_SUCCESS}✅ ${BOX} authorized the mon key${C_RESET}"
    else
        echo -e "   ${C_WARN}⚠️  ${BOX} unreachable - not linked${C_RESET}"
        continue
    fi

    SSH_CONFIG_BLOCK+="
Host ${BOX}
  HostName ${BOX_HOST}
  User ${BOX_USER}
  Port ${BOX_PORT}
  IdentityFile ~/.ssh/id_ed25519
  StrictHostKeyChecking accept-new
"
done

# 8. Write the mon box's ssh config in one shot. Rewritten rather than appended
#    so re-running after a box is destroyed and recreated (new IP, new port)
#    leaves no stale entry pointing somewhere that no longer exists.
if [ -n "$SSH_CONFIG_BLOCK" ]; then
    ssh -q "$MON_BOX" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat > ~/.ssh/config && chmod 600 ~/.ssh/config" << EOF
# Generated by 'make vps-mon-setup' - do not edit by hand.
# Regenerated in full on every run, so destroyed boxes leave no stale entries.
$SSH_CONFIG_BLOCK
EOF
    echo -e "   ${C_SUCCESS}✅ ssh config written on ${MON_BOX}${C_RESET}"
fi

# 9. Prove it works from there, rather than declaring success from here. The
#    mon box's own readiness report is the honest verdict.
echo -e "\n${C_INFO}🔎 Verifying from the mon box...${C_RESET}"
echo "----------------------------------------"

ssh -q -t "$MON_BOX" "cd '${MON_REMOTE_PATH}/mon' && make mon-check" || true

echo "----------------------------------------"
echo ""
echo -e "${C_SUCCESS}✅ Mon box ready.${C_RESET}"
echo -e "   ${C_INFO}Use it with:${C_RESET} ${C_HIGH}ssh ${MON_BOX} -t 'cd ${MON_REMOTE_PATH}/mon && make mon-apps'${C_RESET}"
echo -e "   ${C_INFO}Or read${C_RESET} ${C_HIGH}mon/OPERATING.md${C_RESET}${C_INFO} for the full routine.${C_RESET}"
echo ""
